name: Test Playbook

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible
        run: brew install ansible

      - name: Install Ansible requirements
        run: ansible-galaxy install -r requirements.yml

      - name: Fix Homebrew permissions
        run: |
          sudo chown -R $(whoami) /opt/homebrew
          sudo mkdir -p /opt/homebrew/Caskroom
          sudo chown -R $(whoami) /opt/homebrew/Caskroom

      - name: Run playbook
        run: |
          rm -f ~/.gitconfig
          ansible-playbook setup.yml --become -e "dotfiles_repo=https://github.com/enarmontas/dotfiles.git"
